name: helping_hand
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  firebase_ui_auth: ^1.14.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_multi_formatter: ^2.12.8
  flutter_password_strength: ^0.1.6
  google_places_autocomplete_text_field: ^0.1.3
  google_places_flutter: ^2.0.8
  http: ^1.2.1
  image_picker: ^1.1.1
  intl_phone_number_input:
    git:
      url: https://github.com/Shahidbangash/intl_phone_number_input.git
      ref: develop 
  provider: ^6.0.0
  validation_pro: ^1.1.0

  path: ^1.9.0
  firebase_app_check: ^0.3.0+1
  animated_rating_stars: ^1.0.1
  flip_card: ^0.7.0
  auto_size_text: ^3.0.0
  rxdart:  ^0.27.7
  json_annotation: ^4.9.0
  flutter_toggle_tab: ^1.4.1

  flutter_speed_dial: ^7.0.0
  progressive_time_picker: ^1.0.1
  time_picker_spinner_pop_up: ^2.0.0
  syncfusion_flutter_datepicker: ^27.1.51
  intl: ^0.19.0
  chat_bubbles: ^1.6.0
  cached_network_image: ^3.3.1
  camera: ^0.11.0+2
  flutter_rating_stars: ^1.1.0
  loading_animation_widget: ^1.3.0
  google_mobile_ads: ^5.1.0
  camerawesome: ^2.0.1

  carousel_slider: ^4.2.1


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/logoHH.png
    - assets/emptyProfilePic.png
    - bruh.env