// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXx5kwANznJAtyYAzzykLgg6uj7j9MQP4',
    appId: '1:910001337705:web:3504848f30aff5dc3d39f8',
    messagingSenderId: '910001337705',
    projectId: 'helping-hand-9002c',
    authDomain: 'helping-hand-9002c.firebaseapp.com',
    storageBucket: 'helping-hand-9002c.appspot.com',
    measurementId: 'G-ZQD128GY29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9RZ2-owJveB7mOwjB5SDkTvmPDWJmjVs',
    appId: '1:910001337705:android:cc7bf2553f9347c53d39f8',
    messagingSenderId: '910001337705',
    projectId: 'helping-hand-9002c',
    storageBucket: 'helping-hand-9002c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ZFlDM-RIxqMu575wo7CmTZohCiFmYHg',
    appId: '1:910001337705:ios:4b7f2da181087aee3d39f8',
    messagingSenderId: '910001337705',
    projectId: 'helping-hand-9002c',
    storageBucket: 'helping-hand-9002c.appspot.com',
    iosBundleId: 'com.example.helpingHand',
  );

}